version: '3'
services:
  dash_app:
    build: .
    container_name: dash_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: gunicorn --timeout 120 -b 0.0.0.0:8080 app:server -w 4
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # In case you want to enable HTTPS later
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dash_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
